table shipments
	lineageTag: 3d46f4e4-a7d6-40b3-a4e1-f6171ba5d723

	column 'Sales Person'
		dataType: string
		lineageTag: b886b9f3-bd15-4477-9ed2-1c1aaf042c2f
		summarizeBy: none
		sourceColumn: Sales Person

		annotation SummarizationSetBy = Automatic

	column Geography
		dataType: string
		lineageTag: 02024fa9-8d59-4d5e-8ac1-1f5938556525
		summarizeBy: none
		sourceColumn: Geography

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: fe0a11e8-a260-4787-b303-62ab8eb18190
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 449a4d79-aca1-40cb-897a-25a942d15e20
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Sales
		dataType: double
		lineageTag: 780ad780-f30e-4399-ac3b-43055da32215
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Boxes
		dataType: int64
		formatString: 0
		lineageTag: 975985ca-e2c1-4ad1-a3c7-592f3236ea75
		summarizeBy: sum
		sourceColumn: Boxes

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"shipments","TableItemName":"Boxes (bins)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column 'Boxes (bins)' =
			IF(
				ISBLANK('shipments'[Boxes]),
				BLANK(),
				INT('shipments'[Boxes] / 20) * 20
			)
		formatString: 0
		lineageTag: dede975a-dfb9-4ad1-8b83-b4506596b85f
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "shipments"
				          }
				        },
				        "Property": "Boxes"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 20.0,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"s","Entity":"shipments"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"Boxes"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"Boxes"}},"Size":20.0}}}}

		annotation SummarizationSetBy = Automatic

	partition shipments = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Gypsy\Downloads\ac-sample-data.xlsx"), null, true),
				    shipments_Table = Source{[Item="shipments",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(shipments_Table,{{"Sales Person", type text}, {"Geography", type text}, {"Product", type text}, {"Date", type date}, {"Sales", type number}, {"Boxes", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

